### ISSUE TITLE
Twitter tweets stats update

### ISSUE THREAD

**Issue by ghost** [matteing/makerlog#4] opened 2018-10-28 18:02 UTC
Twitter stats are not realtime in the profile dashboard?

**Comment by matteing** [comment] 2018-10-28 18:13
This is actually by design - it refreshes about once every 24 hours, as having it refresh realtime would be extremely resource intensive. You can force a refresh by changing to a fake one then to your real one if you wish.

Closing - wontfix.

**Closed as completed by matteing** 2018-10-28 18:13 UTC
Labels: wontfix
